cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.CartDetailView.as_view(), name='details'),
    path('add/<slug:slug>', views.AddToCartView.as_view(), name='add_to_cart'),
    path('update-item/', views.UpdateCartItemView.as_view(), name='update_quantity'),
    path('delete-item/', views.DeleteCartItemView.as_view(), name='delete_item'),
    path('clear/', views.ClearCartView.as_view(), name='clear'),
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('catalog/', views.CatalogView.as_view(), name='catalog_all'),
    path('catalog/<slug:category_slug>', views.CatalogView.as_view(), name='catalog'),
    path('product/<slug:slug>', views.ProductDetails.as_view(), name='product')
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
    path('cart/', include('cart.urls', namespace='cart')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('profile/', views.profile_view, name='profile'),
    path('edit-account-details/', views.edit_account_details, name='edit-account-details'),
    path('logout/', views.logout_view, name='logout'),
]

main/models.py
from django.db import models
from django.utils.text import slugify

class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.CharField(max_length=100, unique=True)
    
    def save(self, *args , **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)
        
    def __str__(self):
        return f'{self.name} - {self.slug}'
    

class Material(models.Model):
    name = models.CharField(max_length=100)
    
    def __str__(self):
        return f'{self.name}'
    
    
class Size(models.Model):
    name = models.CharField(max_length=10, unique=True)
        
    def __str__(self):
        return f'{self.name}'
    

class Product(models.Model):
    name = models.CharField(max_length=100)
    slug = models.CharField(max_length=100, unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products')
    description = models.TextField()
    main_image = models.ImageField(upload_to='product/main-image/')
    color = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    
    def __str__(self):
        return f'{self.name}'
    
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)
        
        
class ProductSize(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='product_sizes')
    size = models.ForeignKey(Size, on_delete=models.CASCADE)
    stock = models.PositiveIntegerField(default=0)
    on_stock = models.BooleanField(default=False)
    
    
    def __str__(self):
        return f"{self.size.name} ({self.stock} in stock for {self.product.name})"
    
    
    def save(self, *args, **kwargs):
        if self.stock > 0:
            self.on_stock = True
        else:
            self.on_stock = False
        super().save(*args, **kwargs)
        
        
class ProductMaterial(models.Model):
    prodct = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='product_materials')
    material = models.ForeignKey(Material, on_delete=models.CASCADE)
    percentage = models.PositiveIntegerField()
    
    def __str__(self):
        return f'{self.prodct.name} - {self.material.name} ({self.percentage}%)'

main/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import TemplateView, ListView, DetailView
from django.db.models import Q
from django.template.response import TemplateResponse
from .models import Category, Product, Size


class IndexView(TemplateView):
    template_name = 'base.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context
    
    
    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        if request.headers.get('HX-Request'):
            return TemplateResponse(request, 'main/home.html', context)
        return TemplateResponse(request, self.template_name, context)
    
    
class CatalogView(ListView):
    template_name = 'main/catalog.html'
    model = Product
    context_object_name = 'products'
    ordering = ['-created_at']
    
    # Filtration functions for get_queryset method
    FILTER_FUNC = {
        'min_price': lambda queryset, value: queryset.filter(price__gte=value),
        'max_price': lambda queryset, value: queryset.filter(price__lte=value), 
        'color': lambda queryset, value: queryset.filter(color__iexact=value), 
        'size': lambda queryset, value: queryset.filter(product_size__size__name=value), 
        'on_stock': lambda queryset, value: queryset.filter(product_size__on_stock=value),
    }
    
    def get_queryset(self):
        qs = super().get_queryset()
        category_slug = self.kwargs.get('category_slug')
        
        if category_slug:
            current_category = get_object_or_404(Category, slug=category_slug)
            qs = qs.filter(category=current_category)            
        
        for params, filter_func in self.FILTER_FUNC.items():
            value = self.request.GET.get(params)
            if value:
                qs = filter_func(qs, value)
        return qs
    
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        context['sizes'] = Size.objects.all()
        
        for param in self.FILTER_FUNC.keys():
            context[param] = self.request.GET.get(param, '')
                
        return context
        

class ProductDetails(DetailView):
    model = Product
    template_name = 'main/product_detail.html'
    context_object_name = 'product'
    slug_field = 'slug'
    slug_url_kwarg = 'slug'
    
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product = self.get_object()
        context['current_category'] = product.category.slug
        context['similar_products'] = Product.objects.filter(
            category=product.category).exclude(id=product.id)[:4]
        return context

templates/main/catalog.html
{% extends 'base.html' %}
{% block header %}
  {% include 'main/header.html' %}
{% endblock %}

{% block content %}
  <div class="flex lg:mx-8 lg:my-4">
    <div class="mr-3">
      <ul class="space-y-1">
        {% if categories %}
          <li>
            <a href="{% url 'main:catalog_all' %}" class="text-xl text-gray-900 hover:text-gray-600 transition-colors duration-300">all</a>
          </li>
          {% for category in categories %}
            <li>
              <a href="{% url 'main:catalog' category.slug %}" class="text-xl text-gray-900 hover:text-gray-600 transition-colors duration-300">{{ category.name }}</a>
            </li>
          {% endfor %}
          <p class="text-xl text-gray-900">FILTERS</p>
        {% else %}
          <p class="text-gray-900 text-2xl">No avalible categories</p>
        {% endif %}
      </ul>
    </div>
    <div>
      {% if products %}
        {% include 'main/partials/items_catalog.html' %}
      {% else %}
        <p>NO AVALIBLE PRODUCTS</p>
      {% endif %}
    </div>
  </div>
{% endblock %}

templates/main/header.html
<header>
  <div class="mx-auto my-4 px-4 sm:px-6 lg:px-8 flex justify-between items-center">
    <div>
      <a href="{% url 'main:index' %}"><h1 class="text-gray-900 text-6xl hover:text-gray-600 transition-colors duration-300">ShopName</h1></a>
    </div>
    <div>
      <ul class="flex space-x-5">
        <li>
          <a href="{% url 'main:catalog_all' %}" class="text-xl text-gray-900 hover:text-gray-600 transition-colors duration-300">shop</a>
        </li>
        <li>
          <a href="#" class="text-xl text-gray-900 hover:text-gray-600 transition-colors duration-300">contact</a>
        </li>
        <li>
          <a href="{% url 'users:profile' %}" class="text-xl text-gray-900 hover:text-gray-600 transition-colors duration-300">account</a>
        </li>
        <li>
          <a href="{% url 'cart:details' %}" class="text-xl text-gray-900 hover:text-gray-600 transition-colors duration-300">cart ({{ total_items }})</a>
        </li>
      </ul>
    </div>
  </div>
</header>

templates/main/home.html
<div class="relative h-screen w-full overflow-hidden">
  <nav class="absolute left-6 top-1/2 -translate-y-1/2 z-20">
    <ul class="space-y-2">
      <li>
        <a href="{% url 'main:catalog_all' %}" class="text-lg text-gray-900 hover:text-gray-600 transition-colors duration-300">shop</a>
      </li>
      <li>
        <a href="#" class="text-lg text-gray-900 hover:text-gray-600 transition-colors duration-300">contact</a>
      </li>
      <li>
        <a href="{% url 'users:profile' %}" class="text-lg text-gray-900 hover:text-gray-600 transition-colors duration-300">account</a>
      </li>
      <li>
        <a href="{% url 'cart:details' %}" class="text-lg text-gray-900 hover:text-gray-600 transition-colors duration-300">cart ({{ total_items }})</a>
      </li>
    </ul>
  </nav>
  <div class="absolute inset-0 flex items-center justify-center z-10">
    <h1 class="text-9xl font-bold text-gray-900">ShopName</h1>
  </div>
</div>

templates/main/product_detail.html
{% extends 'base.html' %}

{% block header %}
  {% include 'main/header.html' %}
{% endblock %}

{% block content %}
  <div class="lg:mx-8 lg:mt-8">
    <p class="text-gray-800 text-lg">
      <a href="{% url 'main:catalog_all' %}" class="hover:text-gray-600 duration-300">CATALOG</a> /
      <a href="{% url 'main:catalog' product.category.slug %}" class="hover:text-gray-600 duration-300">{{ product.category.slug|upper }}</a> /
      {{ product.slug|upper }}
    </p>
    <div class="lg:flex mt-3 gap-10">
      <div class="flex justify-center lg:block">
        <img src="{{ product.main_image.url }}" alt="{{ product.name }} image" class="max-w-xs sm:max-w-xl lg:max-w-2xl" />
      </div>
      <!-- Приклад як зробити контейнер на сайті -->
      <div class="mt-6 lg:mt-0 max-w-xl px-2">
        <div class="mb-4">
          <h3 class="text-2xl font-bold text-gray-900 mb-2">{{ product.name }}</h3>
          <p class="text-3xl font-semibold text-gray-800">{{ product.price }} €</p>
        </div>
        <div class="mb-6">
          <p class="text-sm text-gray-600 mb-2">Description:</p>
          <p class="text-gray-700 leading-relaxed">{{ product.description }}</p>
        </div>
        <!-- Add to cart block -->
        <div>
          <form action="{% url 'cart:add_to_cart' product.slug %}" method="post">
            {% csrf_token %}
            <h2 class="text-gray-900 text-2xl">Size</h2>
            {% if product.product_sizes.all %}
              <div class="flex flex-wrap gap-2">
                {% for product_size in product.product_sizes.all %}
                  <div>
                    <input type="hidden" name="quantity" value="1">
                    <input type="radio" name="size_id" id="size-{{ product_size.id }}" value="{{ product_size.id }}" class="hidden peer" {% if not product_size.on_stock %}disabled{% endif %}/>
                    <label for="size-{{ product_size.id }}" 
                    class="
                    {% if not product_size.on_stock %} 
                      cursor-not-allowed inline-block px-4 py-2 border-2 border-gray-300 rounded-lg transition-all duration-300 text-gray-700 font-medium text-center min-w-[50px] bg-gray-400
                    {% else %} 
                      inline-block px-4 py-2 border-2 border-gray-300 rounded-lg cursor-pointer transition-all duration-300 text-gray-700 font-medium text-center min-w-[50px] hover:border-gray-900 hover:bg-gray-50 hover:text-gray-900 peer-checked:bg-gray-900 peer-checked:text-white peer-checked:border-gray-900 active:scale-95 peer-disabled:bg-gray-400 
                    {% endif %}">{{ product_size.size.name }}</label>
                  </div>
                {% endfor %}
              </div>
            {% else %}
              <div class="border-2 border-gray-900 px-3 py-3 text-xl max-w-xl text-center">Not avalible sizes</div>
            {% endif %}
            <div class="flex gap-4 mt-4">
              <button class="bg-gray-900 text-white px-6 py-3 hover:bg-gray-700 transition-colors duration-300" type="submit">Add to Cart</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  <!-- Similar items -->
  {% if similar_products %}
    {% include 'main/partials/similar_items.html' %}
  {% else %}
    <div class="text-gray-900 max-w-xl border-1 border-gray-900">No similar items</div>
  {% endif %}
{% endblock %}