cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.CartDetailView.as_view(), name='details'),
    path('add/<slug:slug>', views.AddToCartView.as_view(), name='add_to_cart'),
    path('update-item/', views.UpdateCartItemView.as_view(), name='update_quantity'),
    path('delete-item/', views.DeleteCartItemView.as_view(), name='delete_item'),
    path('clear/', views.ClearCartView.as_view(), name='clear'),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
    path('cart/', include('cart.urls', namespace='cart')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('profile/', views.profile_view, name='profile'),
    path('edit-account-details/', views.edit_account_details, name='edit-account-details'),
    path('logout/', views.logout_view, name='logout'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.utils.html import strip_tags


class CustomUserManager(BaseUserManager):
    def create_user(self, email, first_name, last_name, password=None, **extra_fields):
        if not email:
            raise ValueError('Email field cannot be empty')
        email = self.normalize_email(email)
        user = self.model(email=email, first_name=first_name, last_name=last_name, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        
    
    def create_superuser(self, email, first_name, last_name, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        
        if not extra_fields.get('is_staff'):
            raise ValueError('Superuser must have is_staff=true')
        elif not extra_fields.get('is_superuser'):
            raise ValueError('Superuser must have is_superuser=true')
        
        return self.create_user(email, first_name, last_name, password, **extra_fields)


class CustomUser(AbstractUser):
    email = models.EmailField(max_length=250, unique=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    country = models.CharField(max_length=100, blank=True, null=True)
    city = models.CharField(max_length=100, blank=True, null=True)
    address = models.CharField(max_length=100, blank=True, null=True)
    postal_code = models.CharField(max_length=20, blank=True, null=True)
    
    def __str__(self):
        return f'{self.email} {self.first_name} {self.last_name}'
    
    
    username = CustomUserManager()
    
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']
    
    def clean(self):
        fields = ['country', 'city', 'address', 'postal_code']
        for field in fields:
            value = getattr(self, field)
            if value:
                setattr(self, field, strip_tags(value))
    

users/forms.py
from django import forms
from django.utils.html import strip_tags
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import get_user_model, authenticate
from .models import CustomUser

User = get_user_model()


class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(max_length=250, required=True, widget=forms.EmailInput(
        attrs={'placeholder': 'EMAIL',
               'class': 'border-1 border-gray-900 text-lg focus:outline-none focus:ring-1 focus:ring-gray-400 focus:border-gray-400'}))
    first_name = forms.CharField(max_length=50, required=True, widget=forms.TextInput(
        attrs={'placeholder': 'FIRST NAME',
               'class': 'border-1 borber-gray-900 text-lg focus:outline-none focus:ring-1 focus:ring-gray-400 focus:border-gray-400'}))
    last_name = forms.CharField(max_length=50, required=True, widget=forms.TextInput(
        attrs={'placeholder': 'LAST NAME',
               'class': 'border-1 border-gray-900 text-lg focus:outline-none focus:ring-1 focus:ring-gray-400 focus:border-gray-400'}))
    password1 = forms.CharField(max_length=250, required=True, widget=forms.PasswordInput(
        attrs={'placeholder': 'PASSWORD1',
               'class': 'border-1 border-gray-900 text-lg focus:outline-none focus:ring-1 focus:ring-gray-400 focus:border-gray-400'}))
    password2 = forms.CharField(max_length=250, required=True, widget=forms.PasswordInput(
        attrs={'placeholder': 'PASSWORD2',
               'class': 'border-1 border-gray-900 text-lg focus:outline-none focus:ring-1 focus:ring-gray-400 focus:border-gray-400'}))
    
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'password1', 'password2']
        
    
    def clean_email(self):
        data = self.cleaned_data.get('email')
        if User.objects.filter(email=data).exists():
            raise forms.ValidationError('User with this email is already exists')
        return data
        
        
    def save(self, commit=True):
        user = super().save(commit=False)
        user.username = None
        if commit:
            user.save()
        return user


class CustomUserLoginForm(AuthenticationForm):
    username = forms.CharField(required=True, max_length=250, widget=forms.EmailInput(
        attrs={'placeholder': 'EMAIL', 
               'class': 'border-1 border-gray-900 text-lg focus:outline-none focus:ring-1 focus:ring-gray-400 focus:border-gray-400'}))
    password = forms.CharField(required=True, max_length=250, widget=forms.PasswordInput(
        attrs={'placeholder': 'PASSWORD', 
               'class': 'border-1 border-gray-900 text-lg focus:outline-none focus:ring-1 focus:ring-gray-400 focus:border-gray-400'}))

    
    def clean(self):
        email = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        
        self.user_cache = authenticate(self.request, username=email, password=password)
        
        if self.user_cache is None:
            raise forms.ValidationError('Invalid password or email')
        elif not self.user_cache.is_active:
            raise forms.ValidationError('User is inactive')
        return self.cleaned_data
    
    
class CustomUserUpdateForm(forms.ModelForm):
    email = forms.EmailField(max_length=250, required=False, widget=forms.EmailInput(
        attrs={'placeholder':'EMAIL', 
               'class': 'border-1 border-gray-900 text-lg focus:outline-none focus:ring-1 focus:ring-gray-400 focus:border-gray-400'}))
    first_name = forms.CharField(max_length=50, required=True, widget=forms.TextInput(
        attrs={'placeholder':'FIRST NAME',
               'class': 'border-1 border-gray-900 text-lg focus:outline-none focus:ring-1 focus:ring-gray-400 focus:border-gray-400'}))
    last_name = forms.CharField(max_length=50, required=True, widget=forms.TextInput(
        attrs={'placeholder':'LAST NAME',
               'class': 'border-1 border-gray-900 text-lg focus:outline-none focus:ring-1 focus:ring-gray-400 focus:border-gray-400'}))
    country = forms.CharField(max_length=100, required=True, widget=forms.TextInput(
        attrs={'placeholder':'COUNTRY',
               'class': 'border-1 border-gray-900 text-lg focus:outline-none focus:ring-1 focus:ring-gray-400 focus:border-gray-400'}))
    city = forms.CharField(max_length=100, required=True, widget=forms.TextInput(
        attrs={'placeholder':'CITY',
               'class': 'border-1 border-gray-900 text-lg focus:outine-none focus:ring-1 focus:ring-gray-400 focus:border-gray-400'}))
    address = forms.CharField(max_length=100, required=True, widget=forms.TextInput(
        attrs={'placeholder':'ADDRESS',
               'class': 'border-1 border-gray-900 text-lg focus:outline-none focus:ring-1 focus:ring-gray-400 focus:border-gray-400'}))
    postal_code = forms.CharField(max_length=20, required=True, widget=forms.TextInput(
        attrs={'placeholder':'POSTAL CODE',
               'class': 'border-1 border-gray-900 text-lg focus:outline-none focus:ring-1 focus:ring-gray-400 focus:border-gray-400'}))
    
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'country', 'city', 'address', 'postal_code']
        
        
    def clean_email(self):
        email = self.cleaned_data.get('email')
        if email and CustomUser.objects.filter(email=email).exclude(id=self.instance.id).exists():
            raise forms.ValidationError('User with this email is already exists')
        return email
    
    
    def clean(self):
        cleaned_data = super().clean()
        if not cleaned_data.get('email'):
            cleaned_data['email'] = self.instance.email
        
        for field in ['country', 'city', 'postal_code', 'address']:
            if cleaned_data.get(field):
                cleaned_data[field] = strip_tags(cleaned_data[field])
        return cleaned_data

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout
from django.views.decorators.csrf import csrf_protect
from .forms import CustomUserCreationForm, CustomUserLoginForm, CustomUserUpdateForm
from .models import CustomUser
from cart.views import CartMixin


def register_view(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        old_session = request.session.session_key
        if form.is_valid():
            user = form.save()
            login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            cart_mixin = CartMixin()
            cart_mixin.merge_carts(request, old_session)
            return redirect('main:index')
    else:
        form = CustomUserCreationForm()
    return render(request, 'users/register.html', {'form': form})

@csrf_protect
def login_view(request):
    if request.method == 'POST':
        form = CustomUserLoginForm(request=request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            old_session = request.session.session_key
            login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            cart_mixin = CartMixin()
            cart_mixin.merge_carts(request, old_session)            
            return redirect('main:index')
    else:
        form = CustomUserLoginForm
    return render(request, 'users/login.html', {'form': form})


@login_required(login_url='/users/login')
def profile_view(request):
    user = CustomUser.objects.get(id=request.user.id)
    return render(request, 'users/profile.html', {'user': user})


@login_required(login_url='/users/login')
def edit_account_details(request):
    if request.method == 'POST':
        form = CustomUserUpdateForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('users:profile')
    else:
        form = CustomUserUpdateForm(instance=request.user)
    return render(request, 'users/edit_account_details.html', {'form': form})


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('main:index')
    return render(request, 'users/logout_confirm.html')

templates/users/edit_account_details.html
{% extends 'base.html' %}

{% block content %}
  <div class="relative h-screen w-full overflow-hidden">
    <div class="absolute inset-0 flex items-center justify-center">
      <form action="{% url 'users:edit-account-details' %}" method="post" class="max-w-2xl shadow-xl/30 px-3 py-3">
        {% csrf_token %}
        <div class="grid grid-cols-1 mb-6">{{ form.email }}</div>
        <div class="grid grid-cols-2 mb-6 gap-10">
          <div>{{ form.first_name }}</div>
          <div>{{ form.last_name }}</div>
        </div>
        <div class="grid grid-cols-2 mb-6 gap-10">
          <div>{{ form.country }}</div>
          <div>{{ form.city }}</div>
        </div>
        <div class="grid grid-cols-2 gap-10 mb-6">
          <div>{{ form.address }}</div>
          <div>{{ form.postal_code }}</div>
        </div>
        <div class="grid grid-cols-1">
          <button type="submit" class="px-3 py-3 border-2 border-gray-900 text-gray-900 text-xl hover:text-gray-200 hover:bg-gray-900 transition-color duration-700">Edit data</button>
        </div>
      </form>
    </div>
  </div>
{% endblock %}

templates/users/login.html
{% extends 'base.html' %}
{% block content %}
  <div class="relative h-screen w-full overflow-hidden">
    <div class="absolute inset-0 flex items-center justify-center">
      <form action="{% url 'users:login' %}" method="post" class="shadow-xl/30 mx-w-2xl px-3 py-3">
        {% csrf_token %}
        <div class="grid grid-cols-2 gap-10 mb-6">
          <div>{{ form.username }}</div>
          <div>{{ form.password }}</div>
        </div>
        <div class="grid grid-cols-2 gap-10">
          <button type="submit" class="text-center text-xl px-3 py-3 border-1 border-gray-900 hover:text-gray-200 hover:bg-gray-900 transition-color duration-700">Log in</button>
          <a href="{% url 'users:register' %}" class="text-center text-xl px-3 py-3 border-1 border-gray-900 hover:text-gray-300 hover:bg-gray-900 transition-color duration-700">Create account</a>
        </div>
      </form>
    </div>
  </div>
{% endblock %}

templates/users/logout_confirm.html
{% extends 'base.html' %}
{% block content %}
  <div class="relative h-screen w-full overflow-hidden">
    <div class="absolute inset-0 flex items-center justify-center">
      <form action="{% url 'users:logout' %}" method="post" class="shadow-xl/30 max-w-lg px-3 py-3">
        {% csrf_token %}
        <div class="grid grid-cols-2 gap-10">
          <button class="border-2 border-gray-900 text-xl text-gray-900 hover:bg-gray-900 hover:text-gray-300 transition-color duration-700 cursor-pointer" type="submit">logout</button>
          <a href="{% url 'users:profile' %}" class="text-center px-3 py-3 border-2 border-gray-900 text-xl text-gray-900 hover:text-gray-300 hover:bg-gray-900 transition-color duration-700">Back to profile</a>
        </div>
      </form>
    </div>
  </div>
{% endblock %}

templates/users/profile.html
{% extends 'base.html' %}

{% block header %}
  {% include 'main/header.html' %}
{% endblock %}

{% block content %}
  <div class="flex lg:mx-8 lg:gap-8">
    <!-- Menu -->
    {% include 'users/partials/menu.html' %}
    <!-- User data -->
    {% include 'users/partials/user_data.html' %}
  </div>
{% endblock %}

templates/users/register.html
{% extends 'base.html' %}
{% block content %}
  <div class="relative h-screen w-full overflow-hidden">
    <div class="absolute inset-0 flex items-center justify-center">
      <form method="post" action="{% url 'users:register' %}" class="shadow-xl/30 max-w-2xl px-3 py-3">
        {% csrf_token %}
        <div class="grid grid-cols-1 mb-6">{{ form.email }}</div>
        <div class="grid grid-cols-2 gap-10 mb-6">
          <div>{{ form.first_name }}</div>
          <div>{{ form.last_name }}</div>
        </div>
        <div class="grid grid-cols-2 gap-10 mb-6">
          <div>{{ form.password1 }}</div>
          <div>{{ form.password2 }}</div>
        </div>
        <div class="grid grid-cols-2 gap-10">
          <button type="submit" class="px-3 py-3 border-2 border-gray-900 text-gray-900 text-xl hover:text-gray-200 hover:bg-gray-900 transition-color duration-700">Create Account</button>
          <a href="{% url 'users:login' %}" class="text-center px-3 py-3 border-2 border-gray-900 text-xl text-gray-900 hover:text-gray-300 hover:bg-gray-900 transition-color duration-700">Log in</a>
        </div>
      </form>
    </div>
  </div>
{% endblock %}